### ISSUE TITLE
 '500 Internal Server ErrorServer got itself in trouble'

### ISSUE THREAD

**Issue by Troom** [flashspys/docker-nginx-static#12]
Hello.

I have small problem with nginx. Now i'm just trying to host few photos for my other services. On browser, everything work nice. But when i try download content to my C# application i get  response form fiddler:
userMessage=Downloading image from URL 'http://myDomain.org:Port/FileName.png' failed. Server returned the following HTTP status code: 500 INTERNAL_SERVER_ERROR and response body: '500 Internal Server ErrorServer got itself in trouble'.

Update:
I'm also getting this error:
userMessage=Downloading image from URL 'http://myDomain.org:Port/FileName.png' failed. Server returned the following HTTP status code: 504 GATEWAY_TIMEOUT and response body: 'The remote server timed out'.

I change perrmission of static files chmod 777 without any result.
###########
Traefik
How reach my files from traefik? Without treafik i can reach files through
IP:ExternalPort/StaticFileName

When i configure it with traefik, and my services are configured 
Below i show my result of: 
curl -s 127.0.0.1:8080/api/rawdata | jq .)

>     "traefikRouterName@docker": {
>       "entryPoints": [
>         "web"
>       ],
>       "service": "traefikServiceName",
>       "rule": "Host(`myDomain.org`)",
>       "status": "enabled",
>       "using": [
>         "web"
>       ]
>     },
.
> traefikServiceName@docker": {
>       "loadBalancer": {
>         "servers": [
>           {
>             "url": "http://172.25.0.2:80"
>           }
>         ],
>         "passHostHeader": true
>       },
>       "status": "enabled",
>       "usedBy": [
>         "traefikRouterName@docker"
>       ],
>       "serverStatus": {
>         "http://172.25.0.2:80": "UP"
>       }
>     },

docker-compose.yml

>  fileServer:
>       image: flashspys/nginx-static
>       container_name: myDomain.org
>       expose:
>         - 80/tcp
>       labels:
>         - "traefik.enable=true"
>         - "traefik.http.routers.traefikRouterName.rule=Host(`myDomain.org`)"
>         - "traefik.http.routers.traefikRouterName.entrypoints=web"
>       volumes:
>         - /absolute/path/to/staticFiles:/static

The url don't work. Is it my mistake?
> myDomain.org/staticFileName

**Comment by flashspys** [comment]
Hey,

Sorry, but does my image work correctly without traefik or not? The 500 error codes you mentioned are with a high probability not caused by nginx. Double-check if you set your URLs/IPs correctly. 

With that information I would guess you have an issue in your traefik configuration. Double check if traefik and the nginx container are in the same network. Check the traefik log for requests and failures. What I regulary do is do `docker exec -it traefik sh` and check with e.g. curl that this container is able to reach the nginx container.

If you still have issues please go ahead and try to give me as much information as possible and I'll try the best to help you.

**Comment by Troom** [comment]
Yes, your image work without traefik.
Thanks for the info with the reason may not be nginx. I have no knowledge of nginx yet.
I will play with the topic and if I know something more, I will respond.

**Comment by Troom** [comment]
Ok, finally I managed to configure everything.
Reasons for my mistakes:
Wrong setup of treafik network.
The website where I was sending photos required https.

[FileServerConfig.txt](https://github.com/flashspys/docker-nginx-static/files/5001118/FileServerConfig.txt)

Summing up, many thanks for the super light container. 
Fantastic solution that is very easy to configure (as long as you know what you are doing :D).
