### ISSUE TITLE
armv7 support

### ISSUE THREAD

**Issue by Lwtsde** [flashspys/docker-nginx-static#17]
armv7 support is missing.

Tested on Raspberry Pi 3B+ running  Raspbian Buster 10

**Comment by flashspys** [comment]
This is true, there is currently no support for armv7 images. Pull Requests are welcome!

**Comment by theonelucas** [comment]
@flashspys I successfully built this image for linux/arm64/v8 with no changes required! if you could tag it in docker hub so I can remove my local service that'd be awesome.

**Comment by theonelucas** [comment]
> armv7 support is missing.
> 
> Tested on Raspberry Pi 3B+ running Raspbian Buster 10

The error you see is probably `standard_init_linux.go:228: exec user process caused: exec format error` which is caused by Docker itself, as this image is not tagged for arm architecture. If you clone the repository and `docker build .`, then it'll work.

**Comment by flashspys** [comment]
Currently the image is built by docker hub. Can you explain or link a blog article or so how to let docker hub build the arm versions?

**Comment by theonelucas** [comment]
You can inform what architectures to target with `docker buildx`, [this post](https://andrewlock.net/creating-multi-arch-docker-images-for-arm64-from-windows) explains it in detail. I pushed my arm build to [this link](https://hub.docker.com/r/theonelucas/nginx-static) for reference.

**Comment by flashspys** [comment]
ARM versions now available 🎉
