### ISSUE TITLE
Push new image ( & Automated build ? )

### ISSUE THREAD

**Issue by tennox** [flashspys/docker-nginx-static#25]
Would be nice if you would push the latest changes to docker hub.

Also, setting up automated build would be nice. I know docker hub disabled it's free version :(

**Comment by tennox** [comment]
I have forked & created a self-updating version on GitLab:
https://gitlab.com/txlab/docker-nginx-static

**Comment by flashspys** [comment]
Sorry for the delay. The image is now auto updating again, thanks to GitHub actions.

**Comment by maxemann96** [comment]
Fixed in https://github.com/flashspys/docker-nginx-static/pull/26
