### ISSUE TITLE
Docker image out of date - Alpine vulnerability

### ISSUE THREAD

**Issue by Lwtsde** [flashspys/docker-nginx-static#31]
Hi, could you provide a new Docker image in the Docker hub?

Alpine 3.xx - 3.16 has some security vulnerabilities (zlib, busybox) see https://snyk.io/test/docker/alpine:3.16.0.
They are resolved in alpine 3.17.

Thanks in advance :)

**Comment by maxemann96** [comment]
Thanks for the hint. Merge Request is done and will be merged asap.
