### ISSUE TITLE
Getting forbidden error when trying to achieve files

### ISSUE THREAD

**Issue by DevTomaszKrupa** [flashspys/docker-nginx-static#8]
Hi.

I used your image in my docker-compose.yml

**my-http-server:
       image: flashspys/nginx-static
    restart: always
    ports:
      - 12227:80
    volumes: 
      - /home/my-folder:/static**

- '/home/my-folder' is an absolute path.
- the container is running,
-  the directory "themes" exists in "/home/my-folder" 
- 'theme' directory also exists inside the container in /static directory 

and I am getting the forbidden error.

> 2020/04/15 18:16:53 [error] 6#6: *1 directory index of "/static/themes/" is forbidden, client: 31.169.202.8, server: localhost, request: "GET /themes/ HTTP/1.1", host: "192.166.123.176:12227"

**Comment by flashspys** [comment]
Directory listing is disabled (the nginx default) in this container. Thus, if you request folders via HTTP, nginx will behave correctly by not indexing this directory.

**Comment by DevTomaszKrupa** [comment]
You are right! It works for files.
If this is the default behavior of Nginx, I close the issue. Thanks for the quick answer.
