### ISSUE TITLE
Expire Headers ala PageSpeed recommendation

### ISSUE THREAD

**Issue by valoricDe** [flashspys/docker-nginx-static#9]
Wouldn't it make sense to add some expire header rules like:

```
location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to redirecting to index.html
            try_files $uri $uri/ /index.html;
            expires 1w;
            add_header Cache-Control "must-revalidate";
        }

        # Javascript and CSS files
        location ~* \.(?:css|js|json)$ {
            try_files $uri =404;
            expires 1w;
            access_log off;
            add_header Cache-Control "must-revalidate";
        }

        # Media: images, icons, video, audio, HTC
        location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webp|webm|htc|webmanifest)$ {
            expires 1M;
            access_log off;
            add_header Cache-Control "public";
        }

        # Web fonts send expires headers
        location ~* \.(?:eot|otf|ttf|woff|woff2)$ {
          expires 1y;
          access_log off;
          add_header Cache-Control "public";
        }

        # Any route containing a file extension (e.g. /devicesfile.js)
        location ~ ^.+\..+$ {
            try_files $uri =404;
        }
```

**Comment by Empty2k12** [comment]
I think it would make sense for you to start using a custom Nginx config and enable these flags yourself, depending on your use-case.

You can create a custom Nginx config and load it into a Docker container using this image as a base like so:
```
FROM node:alpine
# Build your static files here into a /usr/src/app/build folder, or copy them in from the outside in the next step

FROM flashspys/nginx-static
RUN apk update && apk upgrade
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY mobility-map-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /usr/src/app/build /static
```

The relevant lines are `RUN rm -rf /etc/nginx/conf.d/default.conf` and `COPY my-custom-config.conf /etc/nginx/conf.d/default.conf`. `my-custom-config.conf` should contain the config you posted above.

@flashspys I agree that this can be documented better, and you should provide a link to the default config as a starting point for customization.

**Comment by flashspys** [comment]
I would also suggest to not add any headers. If I'd add these, then someone will come and will comply about the expire times, or want further headers added or removed.
I documented how to change the config in #10 based on @Empty2k12 proposal, are you two guys happy with this?

**Comment by valoricDe** [comment]
What do you think about if we add an alternative nginx.conf as reference for others which care about YSlow etc. with these headers. Or as I understood you don't want to maintain this config right?

**Comment by flashspys** [comment]
Adding an alternative nginx config won't hurt anyone. Do you have a recommendation?

**Comment by valoricDe** [comment]
This is my nginx.conf I'm using now for the static file server
[nginx.conf.txt](https://github.com/flashspys/docker-nginx-static/files/4626062/nginx.conf.txt)

and this is the gzip example configuration I'm using on the proxy:
```
    # can be in http, server or location
    gzip on;
    gzip_comp_level    3;
    gzip_min_length    1024;
    gzip_proxied       any;
    gzip_vary          on;

    gzip_types
    application/atom+xml
    application/javascript
    application/json
    application/ld+json
    application/manifest+json
    application/rss+xml
    application/vnd.geo+json
    application/vnd.ms-fontobject
    application/x-font-ttf
    application/x-web-app-manifest+json
    application/xhtml+xml
    application/xml
    font/opentype
    image/bmp
    image/svg+xml
    image/x-icon
    text/cache-manifest
    text/css
    text/plain
    text/vcard
    text/vnd.rim.location.xloc
    text/vtt
    text/x-component
    text/x-cross-domain-policy;
```
